apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otel-observability.fullname" . }}-app
  namespace: {{ include "otel-observability.namespace" . }}
  labels:
    {{- include "otel-observability.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      {{- include "otel-observability.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        {{- include "otel-observability.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: app
    spec:
      containers:
        - name: app
          image: "{{ .Values.images.app.repository }}:{{ .Values.images.app.tag }}"
          imagePullPolicy: {{ .Values.images.app.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/otel/opentelemetry-javaagent.jar"
            - name: OTEL_SERVICE_NAME
              value: {{ .Values.app.serviceName | quote }}
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "deployment.environment={{ .Values.global.environment }},service.version={{ .Values.app.version }}"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://{{ include "otel-observability.fullname" . }}-collector:{{ .Values.collector.service.otlpGrpcPort }}"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_METRICS_EXPORTER
              value: otlp
            - name: OTEL_LOGS_EXPORTER
              value: otlp
            - name: OTEL_METRIC_EXPORT_INTERVAL
              value: "5000"
          readinessProbe:
            httpGet: { path: /actuator/health, port: http }
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /actuator/health, port: http }
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
