apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ include "otel-observability.namespace" . }}
spec:
  type: {{ .Values.grafana.service.type }}
  selector: { app.kubernetes.io/component: grafana }
  ports:
    - name: http
      port: {{ .Values.grafana.service.port }}
      targetPort: http
      {{- if eq .Values.grafana.service.type "NodePort" }}
      nodePort: {{ .Values.grafana.service.nodePort }}
      {{- end }}
