apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: {{ include "otel-observability.namespace" . }}
spec:
  type: {{ .Values.jaeger.service.type }}
  selector: { app.kubernetes.io/component: jaeger }
  ports:
    - { name: ui, port: {{ .Values.jaeger.service.uiPort }}, targetPort: ui, nodePort: {{ .Values.jaeger.service.uiNodePort }} }
    - { name: otlp-grpc, port: {{ .Values.jaeger.service.otlpGrpcPort }}, targetPort: otlp-grpc }
    - { name: otlp-http, port: {{ .Values.jaeger.service.otlpHttpPort }}, targetPort: otlp-http }
