apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: {{ include "otel-observability.namespace" . }}
  labels:
    {{- include "otel-observability.labels" . | nindent 4 }}
    app.kubernetes.io/component: loki
spec:
  type: {{ .Values.loki.service.type }}
  selector: { app.kubernetes.io/component: loki }
  ports:
    - name: http
      port: {{ .Values.loki.service.port }}
      targetPort: http
      {{- if eq .Values.loki.service.type "NodePort" }}
      nodePort: {{ .Values.loki.service.nodePort | default 31000 }}
      {{- end }}
